Entity\Profile:
  type: entity
  table: profile
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    created_at:
      type: datetime
    updated_at:
      type: datetime
    nickname:
      type: string
    email:
      type: string
      unique: true
    password:
      type: string
